# Generated by Django 4.0.6 on 2023-01-28 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('plate_no', models.CharField(max_length=50)),
                ('check_ac', models.CharField(choices=[('ac', 'AC'), ('non-ac', 'Non-AC')], default='non-ac', max_length=10)),
                ('seat_type', models.CharField(choices=[('ac-seat', 'AC Seat'), ('non-ac-seat', 'Non-AC Seat'), ('ac-sleeper', 'AC Sleeper'), ('non-ac-sleeper', 'Non-AC Sleeper')], default='non-ac-seat', max_length=25)),
                ('max_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stops_city', models.CharField(default='', max_length=100)),
                ('distance', models.CharField(max_length=255)),
                ('boarding_point', models.CharField(blank=True, max_length=50, null=True)),
                ('dropping_point', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_bus', to='booking.bus')),
                ('destination_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_destination_address', to='booking.address')),
                ('origin_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_origin_address', to='booking.address')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('seat_name', models.CharField(max_length=10, unique=True)),
                ('bus_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bus', to='booking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('daysOfWeek', models.CharField(max_length=255)),
                ('route_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_route', to='booking.routes')),
            ],
        ),
        migrations.CreateModel(
            name='BusBookings_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('busbookings_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_details_busbooking', to='booking.busbookings')),
                ('seat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busbooking_details_seat_fk', to='booking.seat')),
            ],
        ),
        migrations.AddField(
            model_name='busbookings',
            name='schedules_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busbookings_schedules', to='booking.schedules'),
        ),
        migrations.AddField(
            model_name='busbookings',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busbookings_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
