# Generated by Django 4.0.6 on 2023-01-31 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('ac-seat(2+1)', 'AC Seat(2+1)'), ('non-ac-seat(2+2)', 'Non-AC Seat(2+2)'), ('ac-sleeper(2+1)', 'AC Sleeper(2+1)'), ('non-ac-sleeper(2+1)', 'Non-AC Sleeper(2+1)')], default='non-ac-seat', max_length=25),
        ),
        migrations.CreateModel(
            name='Special_Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('schedule', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
                ('total_days', models.CharField(max_length=15)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('bus_fk_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tours_bus', to='booking.bus')),
                ('destination_fk_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tours_destination_address', to='booking.address')),
                ('origin_fk_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tours_origin_address', to='booking.address')),
            ],
        ),
    ]
