# Generated by Django 4.0.6 on 2023-01-31 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_bus_seat_type_special_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='STourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('special_tours_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stour_booking_Special_Tours', to='booking.special_tours')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stour_booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='busbookings',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='busbookings',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='busbookings',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='STourBooking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('seat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stourbooking_details_seat_fk', to='booking.seat')),
                ('stourbooking_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stourbooking_details_STourBooking', to='booking.stourbooking')),
            ],
        ),
    ]
