# Generated by Django 4.0.6 on 2023-02-02 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_stourbooking_busbookings_confirm_busbookings_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbookings',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('ac-seat(2+1)', 'AC Seat(2+1)'), ('non-ac-seat(2+2)', 'Non-AC Seat(2+2)'), ('ac-sleeper(2+1)', 'AC Sleeper(2+1)'), ('non-ac-sleeper(2+1)', 'Non-AC Sleeper(2+1)')], default='non-ac-seat(2+2)', max_length=25),
        ),
    ]
