# Generated by Django 4.0.6 on 2023-02-02 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_busbookings_travel_date_alter_bus_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stourbooking',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
