# Generated by Django 4.0.6 on 2023-02-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_special_tours_boarding_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_tours',
            name='offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='special_tours',
            name='offer_per',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
